import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#65dd93',
        'inverse-primary': '#006d3c',
        'tertiary-fixed': '#a4f4bc',
        'on-primary': '#00391d',
        'surface-container-lowest': '#0a0f0d',
        'on-primary-container': '#004424',
        'secondary': '#9bd850',
        'secondary-container': '#68a01a',
        'outline': '#879488',
        'surface-container-low': '#171d1a',
        'tertiary': '#88d7a1',
        'secondary-fixed-dim': '#9bd850',
        'on-primary-fixed-variant': '#00522c',
        'primary-container': '#3fba74',
        'surface-variant': '#303633',
        'inverse-on-surface': '#2c322e',
        'on-background': '#dee4df',
        'on-secondary-fixed-variant': '#2f4f00',
        'tertiary-container': '#67b582',
        'on-surface': '#dee4df',
        'surface-dim': '#0f1512',
        'primary-fixed-dim': '#65dd93',
        'tertiary-fixed-dim': '#88d7a1',
        'on-tertiary': '#00391d',
        'inverse-surface': '#dee4df',
        'error': '#ffb4ab',
        'on-secondary-container': '#1a2f00',
        'primary-fixed': '#82faad',
        'secondary-fixed': '#b6f569',
        'on-primary-fixed': '#00210e',
        'surface-container': '#1b211e',
        'on-error': '#690005',
        'surface-bright': '#343b37',
        'outline-variant': '#3e4a40',
        'surface-container-highest': '#303633',
        'on-surface-variant': '#bdcabd',
        'surface-tint': '#65dd93',
        'on-secondary': '#1f3700',
        'error-container': '#93000a',
        'on-secondary-fixed': '#102000',
        'surface-container-high': '#252b28',
        'surface': '#0f1512',
        'on-tertiary-container': '#004524',
        'background': '#0f1512',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#00210f',
        'on-tertiary-fixed-variant': '#00522c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config
