import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#A1FF6B',
        'primary-hover': '#8BE84F',
        'inverse-primary': '#2FA01A',
        'tertiary-fixed': '#A1FF6B',
        'on-primary': '#0A0C10',
        'surface-container-lowest': '#0a0f0d',
        'on-primary-container': '#0A0C10',
        'secondary': '#A1FF6B',
        'secondary-container': '#8BE84F',
        'outline': '#879488',
        'surface-container-low': '#171d1a',
        'tertiary': '#A1FF6B',
        'secondary-fixed-dim': '#A1FF6B',
        'on-primary-fixed-variant': '#0A0C10',
        'primary-container': '#A1FF6B',
        'surface-variant': '#303633',
        'inverse-on-surface': '#2c322e',
        'on-background': '#dee4df',
        'on-secondary-fixed-variant': '#0A0C10',
        'tertiary-container': '#A1FF6B',
        'on-surface': '#dee4df',
        'surface-dim': '#0f1512',
        'primary-fixed-dim': '#A1FF6B',
        'tertiary-fixed-dim': '#A1FF6B',
        'on-tertiary': '#0A0C10',
        'inverse-surface': '#dee4df',
        'error': '#ffb4ab',
        'on-secondary-container': '#0A0C10',
        'primary-fixed': '#A1FF6B',
        'secondary-fixed': '#A1FF6B',
        'on-primary-fixed': '#0A0C10',
        'surface-container': '#1b211e',
        'on-error': '#690005',
        'surface-bright': '#343b37',
        'outline-variant': '#3e4a40',
        'surface-container-highest': '#303633',
        'on-surface-variant': '#bdcabd',
        'surface-tint': '#A1FF6B',
        'on-secondary': '#0A0C10',
        'error-container': '#93000a',
        'on-secondary-fixed': '#0A0C10',
        'surface-container-high': '#252b28',
        'surface': '#0f1512',
        'on-tertiary-container': '#0A0C10',
        'background': '#0f1512',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#0A0C10',
        'on-tertiary-fixed-variant': '#0A0C10',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config
